// shared/mockData.ts
export const mockVesselsData = [
  {
    name: 'QUEEN MARY 2',
    photoUrl: 'https://placehold.co/64x40/5a67d8/ffffff?text=QM2',
    destinationPort: 'HALIFAX',
    reportedETA: '-',
    reportedDestination: 'CA HAL',
    currentPort: '-',
    imo: '9241061',
    vesselType: 'Passenger Ship',
    flag: 'United Kingdom',
    fleets: ['Cunard'],
    eni: '123456789',
  },
  {
    name: 'EVER GIVEN',
    photoUrl: 'https://placehold.co/64x40/38a169/ffffff?text=EVR',
    destinationPort: 'SINGAPORE',
    reportedETA: '-',
    reportedDestination: 'CNYYY>>SGSGP',
    currentPort: '-',
    imo: '9811000',
    vesselType: 'Container Ship',
    flag: 'Panama',
    fleets: ['Evergreen Marine'],
    eni: '987654321',
  },
  {
    name: 'QUEEN ELIZABETH',
    photoUrl: 'https://placehold.co/64x40/805ad5/ffffff?text=QE',
    destinationPort: 'GLACIER BAY',
    reportedETA: '2025-08-03 21:00 UTC',
    reportedDestination: 'GLACIER BAY',
    currentPort: '-',
    imo: '1477438',
    vesselType: 'Passenger Ship',
    flag: 'United Kingdom',
    fleets: ['Cunard'],
    eni: '555555555',
  },
  {
    name: 'ECLIPSE',
    photoUrl: 'https://placehold.co/64x40/d53f8c/ffffff?text=ECL',
    destinationPort: 'RHODES',
    reportedETA: '2025-08-19 11:00 UTC',
    reportedDestination: 'MARMARIS',
    currentPort: 'MARMARIS',
    imo: '1009613',
    vesselType: 'Yacht',
    flag: 'Cayman Islands',
    fleets: ['Private'],
    eni: '444444444',
  },
  {
    name: 'PAUL R. TREURTHA',
    photoUrl: 'https://placehold.co/64x40/f6ad55/ffffff?text=PRT',
    destinationPort: 'DULUTH SUPERIOR',
    reportedETA: '2025-08-04 00:00 UTC',
    reportedDestination: 'SUPERIOR',
    currentPort: '-',
    imo: '7729057',
    vesselType: 'Cargo Ship',
    flag: 'United States',
    fleets: ['Great Lakes Fleet'],
    eni: '333333333',
  },
  {
    name: 'MAERSK MC-KINNEY MØLLER',
    photoUrl: 'https://placehold.co/64x40/000000/ffffff?text=MMM',
    destinationPort: 'ROTTERDAM',
    reportedETA: '2025-08-05 15:00 UTC',
    reportedDestination: 'NL RTM',
    currentPort: '-',
    imo: '9610121',
    vesselType: 'Container Ship',
    flag: 'Denmark',
    fleets: ['Maersk Line'],
    eni: '222222222',
  },
  {
    name: 'HARMONY OF THE SEAS',
    photoUrl: 'https://placehold.co/64x40/6a5acd/ffffff?text=HOS',
    destinationPort: 'MIAMI',
    reportedETA: '2025-08-06 10:00 UTC',
    reportedDestination: 'US MIA',
    currentPort: '-',
    imo: '9682855',
    vesselType: 'Passenger Ship',
    flag: 'Bahamas',
    fleets: ['Royal Caribbean'],
    eni: '111111111',
  },
];