export const mockData = {
  adminSummary: [
    { title: "Всего пользователей", value: "12,345", color: "#1d4ed8" },
    { title: "Активные за 24ч", value: "3,120", color: "#10b981" },
    { title: "Новые регистрации (мес)", value: "450", color: "#f59e0b" },
    { title: "Ожидают модерации", value: "58", color: "#ef4444" },
  ],
  userActivityData: [
    { name: "Янв", newUsers: 50, activeUsers: 200 },
    { name: "Фев", newUsers: 60, activeUsers: 220 },
    { name: "Мар", newUsers: 75, activeUsers: 250 },
    { name: "Апр", newUsers: 80, activeUsers: 270 },
    { name: "Май", newUsers: 90, activeUsers: 300 },
    { name: "Июн", newUsers: 100, activeUsers: 320 },
  ],
  systemStatusData: [
    { name: "Ошибки", value: 300 },
    { name: "Предупреждения", value: 150 },
    { name: "Инфо", value: 500 },
  ],

  summary: [
    { title: "Total sales", value: "5.2M", color: "#1d4ed8" },
    { title: "Win rate", value: "16.92%", color: "#10b981" },
    { title: "Close rate", value: "14.47%", color: "#ef4444" },
    { title: "Avg days to close", value: "60.70", color: "#f59e0b" },
    { title: "Pipeline value", value: "77.8M", color: "#06b6d4" },
    { title: "Open deals", value: "1.6K", color: "#4f46e5" },
    { title: "Weighted value", value: "35.6M", color: "#f97316" },
    { title: "Avg open deal age", value: "201.67", color: "#ec4899" },
  ],
  dealsWonLast12Months: [
    { name: "May 2024", won: 200, closed: 300 },
    { name: "Jul 2024", won: 450, closed: 500 },
    { name: "Sep 2024", won: 350, closed: 400 },
    { name: "Nov 2024", won: 600, closed: 700 },
    { name: "Jan 2025", won: 550, closed: 650 },
    { name: "Mar 2025", won: 750, closed: 850 },
    { name: "May 2025", won: 900, closed: 1000 },
  ],
  dealsProjection: [
    { name: "May 2025", projected: 2000, dealsDue: 290 },
    { name: "Jul 2025", projected: 3000, dealsDue: 350 },
    { name: "Sep 2025", projected: 2500, dealsDue: 320 },
    { name: "Jan 2026", projected: 3800, dealsDue: 450 },
    { name: "Mar 2026", projected: 4200, dealsDue: 500 },
    { name: "May 2026", projected: 4500, dealsDue: 550 },
  ],
  salesPipeline: [
    { name: "Lead", value: 29.85 },
    { name: "Negotiation", value: 5.66 },
    { name: "Proposal", value: 5.84 },
    { name: "Interview", value: 14.83 },
    { name: "Contact Made", value: 18.49 },
    { name: "Closed Lost", value: 21.32 },
  ],
  dealLossReasons: [
    { name: "Lack of urgency", value: 13.47 },
    { name: "Better alternative", value: 14.81 },
    { name: "Price too high", value: 18.46 },
    { name: "Budget constraints", value: 21.7 },
    { name: "Feature limitations", value: 32.97 },
  ],
  admin: {
    globalMetrics: [
      { title: "Total Users", value: "150", color: "#8b5cf6" },
      { title: "Active Admins", value: "5", color: "#facc15" },
      {
        title: "Total Open Deals (System-wide)",
        value: "1.8K",
        color: "#22d3ee",
      },
      { title: "Average Daily Logins", value: "85", color: "#fb923c" },
    ],
    users: [
      {
        id: "usr001",
        name: "John Doe",
        email: "john.doe@example.com",
        role: "Sales Rep",
        status: "Active",
        lastLogin: "2025-08-03",
      },
      {
        id: "usr002",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        role: "Sales Manager",
        status: "Active",
        lastLogin: "2025-08-04",
      },
      {
        id: "usr003",
        name: "Peter Jones",
        email: "peter.jones@example.com",
        role: "Admin",
        status: "Active",
        lastLogin: "2025-08-04",
      },
      {
        id: "usr004",
        name: "Alice Brown",
        email: "alice.brown@example.com",
        role: "Sales Rep",
        status: "Inactive",
        lastLogin: "2025-07-28",
      },
      {
        id: "usr005",
        name: "Bob White",
        email: "bob.white@example.com",
        role: "Admin",
        status: "Active",
        lastLogin: "2025-08-04",
      },
    ],
    auditLogs: [
      {
        id: "log001",
        timestamp: "2025-08-04 10:30:00",
        user: "Peter Jones",
        action: "Updated Deal Stage: Lead -> Negotiation (Deal ID: D001)",
      },
      {
        id: "log002",
        timestamp: "2025-08-04 09:45:15",
        user: "Bob White",
        action: "Blocked user: Alice Brown",
      },
      {
        id: "log003",
        timestamp: "2025-08-03 16:00:00",
        user: "Peter Jones",
        action: 'Added new Deal Stage: "Follow-up"',
      },
      {
        id: "log004",
        timestamp: "2025-08-03 14:20:00",
        user: "John Doe",
        action: "Closed Deal: D010 (Status: Won)",
      },
    ],
    dealStages: [
      { id: "ds001", name: "Lead", order: 1, weight: 10 },
      { id: "ds002", name: "Contact Made", order: 2, weight: 20 },
      { id: "ds003", name: "Interview", order: 3, weight: 30 },
      { id: "ds004", name: "Proposal", order: 4, weight: 50 },
      { id: "ds005", name: "Negotiation", order: 5, weight: 70 },
      { id: "ds006", name: "Closed Won", order: 6, weight: 100 },
      { id: "ds007", name: "Closed Lost", order: 7, weight: 0 },
    ],
    pipelines: [
      { id: "p001", name: "Main Sales Pipeline" },
      { id: "p002", name: "SMB Sales Pipeline" },
      { id: "p003", name: "Enterprise Sales Pipeline" },
    ],
    dealLabels: [
      { id: "dl001", name: "High Priority" },
      { id: "dl002", name: "Renewal" },
      { id: "dl003", name: "New Client" },
      { id: "dl004", name: "Follow-up Required" },
    ],
  },
};
