export const mockVesselsData = [
  {
    id: "1",
    name: "Ever Given",
    photoUrl:
      "https://cs14.pikabu.ru/post_img/big/2022/04/19/5/1650349086168096537.jpg",
    destinationPort: "Port of Rotterdam",
    reportedETA: "2025-08-15",
    reportedDestination: "Rotterdam",
    currentPort: "Suez",
    imo: "9811000",
    vesselType: "Container Ship",
    flag: "Panama",
    fleets: ["Main Fleet"],
  },
  {
    id: "2",
    name: "Queen Mary 2",
    photoUrl:
      "https://anno-danini.com/assets/images/suda_dlya_perevozki_gruzov.jpg",
    destinationPort: "Port of Southampton",
    reportedETA: "2025-08-20",
    reportedDestination: "Southampton",
    currentPort: "New York",
    imo: "9241061",
    vesselType: "Passenger Ship",
    flag: "United Kingdom",
    fleets: ["Luxury Fleet"],
  },
  {
    id: "3",
    name: "MSC Gülsün",
    photoUrl:
      "https://img.freepik.com/premium-photo/large-cargo-ship-transporting-cargo-international-port_124507-55096.jpg",
    destinationPort: "Port of Hamburg",
    reportedETA: "2025-09-03",
    reportedDestination: "Hamburg",
    currentPort: "Tanger-Med",
    imo: "9839430",
    vesselType: "Container Ship",
    flag: "🇵🇦",
    fleets: ["Main Fleet"],
  },
  {
    id: "4",
    name: "TI Europe",
    photoUrl:
      "https://st2.depositphotos.com/3517931/6106/i/450/depositphotos_61067349-stock-photo-container-ship.jpg",
    destinationPort: "Ras Tanura",
    reportedETA: "2025-09-10",
    reportedDestination: "Ras Tanura",
    currentPort: "Singapore",
    imo: "9254351",
    vesselType: "Crude Oil Tanker",
    flag: "Belgium",
    fleets: ["Energy"],
  },
  {
    id: "5",
    name: "HMM Algeciras",
    photoUrl:
      "https://static.tildacdn.com/tild3338-3134-4434-a633-633432626537/emma-maersk-und-das-.jpg",
    destinationPort: "Port of Hamburg",
    reportedETA: "2025-09-12",
    reportedDestination: "Hamburg",
    currentPort: "Rotterdam",
    imo: "9863297",
    vesselType: "Container Ship",
    flag: "🇲🇹",
    fleets: ["Main Fleet"],
  },
  {
    id: "6",
    name: "Seri Camellia",
    photoUrl:
      "https://www.publicdomainpictures.net/pictures/550000/nahled/vrachtschip-zeeschip-varend-schip-1698130920A9g.jpg",
    destinationPort: "Ras Tanura",
    reportedETA: "2025-09-08",
    reportedDestination: "Ras Tanura",
    currentPort: "Singapore",
    imo: "9690947",
    vesselType: "LNG Carrier",
    flag: "🇲🇾",
    fleets: ["Energy"],
  },
  {
    id: "7",
    name: "OOCL Hong Kong",
    photoUrl:
      "https://static.vesselfinder.net/ship-photo/9487603-304108000-877390d0177006b5fab0bf47a3be315d/1?v1",
    destinationPort: "Port of Rotterdam",
    reportedETA: "2025-09-01",
    reportedDestination: "Rotterdam",
    currentPort: "Tanger-Med",
    imo: "9776171",
    vesselType: "Container Ship",
    flag: "🇭🇰",
    fleets: ["Main Fleet"],
  },
  {
    id: "8",
    name: "Capesize Trader",
    photoUrl:
      "https://st.depositphotos.com/1194815/1208/i/450/depositphotos_12080559-stock-photo-cargo-container-ship.jpg",
    destinationPort: "Port of Hamburg",
    reportedETA: "2025-09-06",
    reportedDestination: "Hamburg",
    currentPort: "Suez",
    imo: "9453454",
    vesselType: "Bulk Carrier",
    flag: "🇵🇦",
    fleets: ["Dry Bulk"],
  },
  {
    id: "9",
    name: "MSC Seaview",
    photoUrl:
      "https://img.freepik.com/premium-photo/merchandise-import-large-blue-cargo-ship-moving-riga-port_378481-270.jpg?semt=ais_hybrid&w=740&q=80",
    destinationPort: "New York",
    reportedETA: "2025-08-30",
    reportedDestination: "New York",
    currentPort: "Southampton",
    imo: "9745378",
    vesselType: "Passenger Ship",
    flag: "🇲🇹",
    fleets: ["Luxury Fleet"],
  },
  {
    id: "10",
    name: "Höegh Tracer",
    photoUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8AJw57TpvLzcS42QdfRPKKlQEsvj0Mf8_3w&s",
    destinationPort: "Port of Southampton",
    reportedETA: "2025-09-04",
    reportedDestination: "Southampton",
    currentPort: "New York",
    imo: "9673381",
    vesselType: "Ro-Ro",
    flag: "🇳🇴",
    fleets: ["Vehicles"],
  },
];
