import type { AdminCompany } from "./types";

export const adminCompaniesMock: AdminCompany[] = [
  {
    id: "1",
    name: "AVS Global Ship Supply",
    category: "Ship Services / Suppliers",
    country: "🇹🇷",
    city: "Istanbul",
    logoUrl: "/logos/avs.png",
    status: "published",
    owner: "admin@avalon.app",
    updatedAt: "2025-08-15T10:00:00Z",
    completeness: 90,
    flags: [],
    tags: ["supplier"],
  },
  {
    id: "2",
    name: "Seven Seas Shipchandlers",
    category: "Ship Services / Suppliers",
    country: "🇦🇪",
    city: "Dubai",
    logoUrl: "/logos/seven-seas.png",
    status: "pending",
    owner: "mod@avalon.app",
    updatedAt: "2025-08-20T12:10:00Z",
    completeness: 75,
    flags: ["needs-review"],
    tags: ["shipchandler"],
  },
  {
    id: "3",
    name: "Stark Shipping",
    category: "Agency",
    country: "🇺🇦",
    city: "Odessa",
    logoUrl: "/logos/stark.png",
    status: "draft",
    owner: "vasilii@avalon.app",
    updatedAt: "2025-08-21T09:40:00Z",
    completeness: 50,
    flags: ["low-quality"],
    tags: ["agency"],
  },
  {
    id: "4",
    name: "Wilhelmsen",
    category: "Agency",
    country: "🇳🇴",
    city: "Oslo",
    logoUrl: "/logos/wilh.png",
    status: "published",
    owner: "admin@avalon.app",
    updatedAt: "2025-08-22T08:15:00Z",
    completeness: 100,
    flags: [],
    tags: ["global"],
  },
  {
    id: "5",
    name: "GAC Shipping",
    category: "Agency",
    country: "🇧🇭",
    city: "Manama",
    logoUrl: "/logos/gac.png",
    status: "suspended",
    owner: "mod@avalon.app",
    updatedAt: "2025-08-18T14:30:00Z",
    completeness: 80,
    flags: ["complaint"],
    tags: ["agency"],
  },
  {
    id: "6",
    name: "Maritime Logistics Co.",
    category: "Logistics",
    country: "🇷🇴",
    city: "Constanța",
    logoUrl: "/logos/mlc.png",
    status: "published",
    owner: "admin@avalon.app",
    updatedAt: "2025-08-24T16:20:00Z",
    completeness: 70,
    flags: [],
    tags: ["logistics"],
  },
  {
    id: "7",
    name: "Baltic Marine",
    category: "Ship Repair",
    country: "🇱🇻",
    city: "Riga",
    logoUrl: "/logos/baltic.png",
    status: "pending",
    owner: "mod@avalon.app",
    updatedAt: "2025-08-19T11:50:00Z",
    completeness: 65,
    flags: [],
    tags: ["repair"],
  },
  {
    id: "8",
    name: "Black Sea Crew",
    category: "Crew Management",
    country: "🇷🇴",
    city: "Bucharest",
    logoUrl: "/logos/bsc.png",
    status: "archived",
    owner: "admin@avalon.app",
    updatedAt: "2025-08-10T07:00:00Z",
    completeness: 60,
    flags: ["duplicate"],
    tags: ["crew"],
  },
  {
    id: "9",
    name: "Port Services Istanbul",
    category: "Port Services",
    country: "🇹🇷",
    city: "Istanbul",
    logoUrl: "/logos/psi.png",
    status: "draft",
    owner: "vasilii@avalon.app",
    updatedAt: "2025-08-23T13:05:00Z",
    completeness: 40,
    flags: ["incomplete"],
    tags: ["port"],
  },
  {
    id: "10",
    name: "Green Anchor",
    category: "Environmental",
    country: "🇬🇷",
    city: "Piraeus",
    logoUrl: "/logos/ga.png",
    status: "published",
    owner: "admin@avalon.app",
    updatedAt: "2025-08-25T09:00:00Z",
    completeness: 85,
    flags: [],
    tags: ["environment"],
  },
];
